name: youtube_sentiment_env
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pip:
      - mlflow==2.9.0
      - scikit-learn==1.3.0
      - pandas==2.0.0
      - numpy==1.24.0
      - scipy==1.10.1
      - joblib==1.3.0
      - matplotlib==3.7.2
